version: '4'

services:
  django:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    hostname: redislocal
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  db:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django_user -d django_db" ]
      interval: 5s
      timeout: 3s
      retries: 2
